export const scholarshipsMockData = [
  {
    id: "1",
    name: "STEM Excellence Scholarship",
    title: "STEM Excellence Scholarship",
    description: "Annual award for students pursuing STEM fields",
    full_description:
      "This scholarship is awarded to outstanding students pursuing Science, Technology, Engineering, and Mathematics fields. We believe in fostering the next generation of innovators and leaders. Recipients will demonstrate academic excellence, leadership potential, and a commitment to using their skills to benefit society.",
    award_amount: "$5,000",
    amount: 5000,
    deadline: "2024-06-30",
    gpa_requirement: "3.5",
    grade_level: ["9th Grade", "10th Grade", "Middle School"],
    citizenship: ["US Citizen", "Permanent Resident"],
    tags: ["STEM", "Full Ride", "First Generation"],
    field: ["Science", "Technology", "Engineering", "Mathematics"],
    field_of_study: "STEM",
    application_url: "https://example.com/apply/stem-scholarship",
  },
  {
    id: "2",
    name: "Community Leaders Fund",
    title: "Community Leaders Fund",
    description: "Supporting students committed to community service",
    full_description:
      "The Community Leaders Fund recognizes students who demonstrate exceptional commitment to service and making a positive impact in their communities. This scholarship supports your academic journey while you continue to inspire others through volunteer work and civic engagement.",
    award_amount: "$3,000",
    amount: 3000,
    deadline: "2024-05-15",
    gpa_requirement: "3.0",
    grade_level: ["Middle School", "9th Grade"],
    citizenship: ["US Citizen", "Permanent Resident"],
    tags: ["Community Service", "Leadership"],
    field: ["General", "Business", "Education"],
    field_of_study: "General",
    application_url: "https://example.com/apply/community-leaders",
  },
  {
    id: "3",
    name: "Women in Tech Scholarship",
    title: "Women in Tech Scholarship",
    description: "Empowering young women in technology careers",
    full_description:
      "This scholarship is dedicated to supporting young women who are passionate about technology and innovation. We aim to increase representation of women in tech fields and provide financial assistance, mentorship, and networking opportunities to help you succeed.",
    award_amount: "$4,500",
    amount: 4500,
    deadline: "2024-07-20",
    gpa_requirement: "3.3",
    grade_level: ["9th Grade", "10th Grade"],
    citizenship: ["US Citizen", "Permanent Resident", "International"],
    tags: ["Women in Tech", "STEM", "Mentorship"],
    field: ["Technology", "Computer Science", "Engineering"],
    field_of_study: "Technology",
    application_url: "https://example.com/apply/women-tech",
  },
]

export const opportunitiesMockData = [
  {
    id: "1",
    name: "Summer STEM Internship Program",
    title: "Summer STEM Internship Program",
    description: "10-week paid internship at a leading tech company",
    full_description:
      "Join our prestigious 10-week summer internship program at one of the world's leading technology companies. You'll work on real projects, develop professional skills, and network with industry experts. Perfect for students interested in gaining hands-on experience in STEM fields.",
    location: "San Francisco, CA",
    duration: "10 weeks",
    deadline: "2024-04-30",
    applicationDeadline: "2024-04-30",
    gpa_requirement: "3.2",
    grade_level: ["9th Grade", "10th Grade"],
    citizenship: ["US Citizen", "Work Visa Eligible"],
    tags: ["Internship", "Paid", "Remote Available"],
    field: ["Technology", "Engineering", "Computer Science"],
    field_name: "Technology",
    type: ["Internship", "Paid", "Summer"],
    application_url: "https://example.com/apply/stem-internship",
  },
  {
    id: "2",
    name: "Global Youth Leadership Program",
    title: "Global Youth Leadership Program",
    description: "3-week international leadership conference",
    full_description:
      "Participate in our transformative 3-week global leadership program where you'll meet young leaders from around the world, attend workshops by industry experts, and engage in community service projects. This program develops critical leadership skills and creates lifelong connections.",
    location: "Virtual + Optional In-Person",
    duration: "3 weeks",
    deadline: "2024-05-10",
    applicationDeadline: "2024-05-10",
    gpa_requirement: "3.0",
    grade_level: ["Middle School", "9th Grade"],
    citizenship: ["US Citizen", "Permanent Resident", "International"],
    tags: ["Leadership", "Virtual", "Global"],
    field: ["General", "Business", "Education"],
    field_name: "General",
    type: ["Conference", "Virtual", "International"],
    application_url: "https://example.com/apply/leadership-program",
  },
  {
    id: "3",
    name: "Environmental Conservation Fellowship",
    title: "Environmental Conservation Fellowship",
    description: "Summer fellowship focused on environmental sustainability",
    full_description:
      "Work alongside environmental scientists and conservation experts this summer. This fellowship offers hands-on experience in field research, data analysis, and project management while contributing to real environmental solutions.",
    location: "Colorado Rockies",
    duration: "8 weeks",
    deadline: "2024-04-15",
    applicationDeadline: "2024-04-15",
    gpa_requirement: "3.1",
    grade_level: ["9th Grade", "10th Grade"],
    citizenship: ["US Citizen"],
    tags: ["Environment", "Research", "Outdoor"],
    field: ["Environmental Science", "Biology", "Sustainability"],
    field_name: "Environmental Science",
    type: ["Fellowship", "Residential", "Research"],
    application_url: "https://example.com/apply/environmental-fellowship",
  },
]

export const blogPostsMockData = [
  {
    id: "1",
    slug: "scholarship-essay-tips",
    title: "Scholarship Essay Tips: Stand Out From the Crowd",
    description: "Learn how to write compelling scholarship essays that grab attention",
    full_description:
      "Writing a compelling scholarship essay is your chance to tell your story and show scholarship committees who you really are. Here are proven strategies to make your essay stand out:\n\n1. Start with a Hook: Begin with an interesting fact, quote, or personal anecdote that captures attention immediately. Avoid clichés and generic openings.\n\n2. Tell Your Story: Scholarship committees want to know about you. Share your background, experiences, and what makes you unique. Be authentic and vulnerable - this is what makes essays memorable.\n\n3. Connect to Your Future: Explain how this scholarship will help you achieve your goals. Be specific about your aspirations and how they connect to your academic and career path.\n\n4. Show Impact: Describe how you've made a difference in your community or school. Use specific examples and quantify your achievements when possible.\n\n5. Edit Ruthlessly: Write multiple drafts. Have teachers, mentors, and friends review your work. Fix grammar, spelling, and awkward phrasing.\n\n6. Follow Directions: Read the prompt carefully and answer exactly what's being asked. Pay attention to word limits and formatting requirements.\n\nRemember, scholarship essays are about showing who you are and why you deserve support. Be genuine, be specific, and let your personality shine through.",
    author: "Sarah Johnson",
    category: "Scholarship Tips",
    image_url: "/scholarship-essay-writing-desk.jpg",
    read_time: "5 min read",
    date: "2024-01-15",
  },
  {
    id: "2",
    slug: "preparing-for-college",
    title: "Essential Guide: Preparing for College as an Underclassman",
    description: "Start your college prep journey early with this comprehensive guide",
    full_description:
      "The best time to start preparing for college is now, even if you're in middle school or early high school. Here's your step-by-step guide:\n\n1. Focus on Academics: Take challenging courses and maintain strong grades. Colleges want to see a consistent record of academic achievement.\n\n2. Get Involved: Join clubs, sports, volunteer, or pursue other extracurricular activities. Colleges want well-rounded students who contribute to their communities.\n\n3. Build Relationships: Develop strong relationships with your teachers and counselors. You'll need recommendation letters later, and these relationships matter.\n\n4. Standardized Testing: Familiarize yourself with the SAT and ACT. Start preparing early so you have time to improve your scores.\n\n5. Explore Career Options: Visit college websites, attend virtual college fairs, and talk to college representatives. Find schools that align with your interests and goals.\n\n6. Save for College: Apply for scholarships early and often. Every scholarship helps reduce your college costs.\n\n7. Develop Life Skills: Learn to manage time, solve problems, and work independently. These skills will help you succeed in college and beyond.\n\nRemember, college preparation is a marathon, not a sprint. Start now, stay focused, and keep working toward your goals.",
    author: "Michael Chen",
    category: "College Prep",
    image_url: "/professional-workplace-office-environment.jpg",
    read_time: "7 min read",
    date: "2024-01-10",
  },
  {
    id: "3",
    slug: "internship-success",
    title: "Internship Success: Making the Most of Your Opportunity",
    description: "Maximize your internship experience with these proven strategies",
    full_description:
      "Getting an internship is exciting, but making the most of it requires strategy and effort. Here's how to have an impactful internship experience:\n\n1. Set Goals: Before your internship starts, identify what you want to learn and accomplish. Share these goals with your supervisor.\n\n2. Show Initiative: Don't wait to be told what to do. Ask questions, volunteer for projects, and look for ways to add value.\n\n3. Build Relationships: Connect with your colleagues and supervisors. These relationships can lead to future job opportunities and valuable references.\n\n4. Ask for Feedback: Regularly check in with your supervisor about your performance. Use feedback to improve and grow.\n\n5. Document Your Work: Keep track of your accomplishments and projects. This material is great for future resumes and interviews.\n\n6. Network: Attend company events and connect with people in your field. Networking is crucial for career development.\n\n7. Reflect and Apply: After your internship, reflect on what you learned and how you'll apply it. Consider how this experience shapes your career path.\n\n8. Thank Everyone: Send thank you notes to your supervisor and colleagues. Maintain these professional relationships.\n\nAn internship is more than just a resume line - it's an opportunity to learn, grow, and start building your professional network.",
    author: "Emily Rodriguez",
    category: "Career Development",
    image_url: "/stem-students-science-laboratory.jpg",
    read_time: "6 min read",
    date: "2024-01-05",
  },
]

export const mockScholarships = scholarshipsMockData
export const mockOpportunities = opportunitiesMockData
export const mockBlogPosts = blogPostsMockData
